DEEPSEEK_API_KEY="sk-32ead3290c8948f7979279fc6a9dd46c"
SUPABASE_URL = "https://wmbgwsphpxagfdnwxjwh.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtYmd3c3BocHhhZ2Zkbnd4andoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc2NDkxMjAsImV4cCI6MjA1MzIyNTEyMH0.Svqi_LU5Nl7Y4sh3W6VHQgmB3kY53l4P5_Jsw7OJYc0"
